'''
The names are generated by the random program, and the seeds are conceived randomly

Not all names are valid
https://www.business.qld.gov.au/industry/liquor-gaming/liquor/guidelines-listing/trading-names-licensed-premises
'''

from .utils import *

def company():
    prefix = ['James Potter\'s', 'Grand Spark', 'Black Hill', 'Tea Park', 'Liberty', 'Mr Chow\'', 'Jonson\'s', \
    'Oliver', 'Hassacci', 'Zhang\'s', 'Mr Corleone\'s', 'Captain Sock\'s', 'Bearman\'s', 'Brandulu']
    business = ['Little Kitchen', 'Restaurant', 'Pizza', 'Coffee', 'Hotel', 'Liquor Shop', 'Bar & Grill', 'Bar', \
    'Noodle House']
    suffix = ['Ltd.', '', '']
    location = ['Sevenfield', 'Bluetown', 'Punch Hills', 'Cool Heights', 'Austin Bay', 'Adanmir Bay']
    
    p = pickone(prefix)
    b = pickone(business)
    s = pickone(suffix)
    l = pickone(location)
    
    # creates two styles, pick either one
    opts = [(' '.join([b, l])).strip(), (' '.join([p, b, s])).strip()]
    pick = random.randint(0, 1)
    if (pickchance(0.7)):
        return opts[1]

    return opts[0]
